app:
  port: 3000
  log_level: info
  crontime: "*/5 * * * *"

uptimerobot:
  api_key: fake_api_key
  pattern: "%group/%name"
  statuses: "2-9"

website:
  title: "Uptime Robot Status"
  copyright: "Uptime Robot"
  links:
    - name: Home
      href: https://uptimerobot.com
    - name: GitHub
      href: https://github.com/giuem/uptimerobot-page
